version: '3'
volumes:
    logs:
        driver: local
services:
    composer:
        image: composer/composer:latest
        environment:
            - COMPOSER_CAHE_DIR=/app/var/cache/composer
        volumes:
            - .:/app
    php:
        image: php:7.4-cli
        volumes:
            - .:/app
        working_dir: /app
    phpunit:
        image: php:7.4-cli
        volumes:
            - .:/app
        working_dir: /app
        entrypoint: vendor/bin/phpunit
    slim:
        image: php:7.4-alpine
        working_dir: /var/www/html
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        ports:
            - 8080:8080
        volumes:
            - .:/var/www/html
            - logs:/var/www/logs